#!/usr/bin/env python3
"""WS-D: generate .claude/skills/ from docs/world-model/model.yaml + docs/info-hierarchy.md.

GPU-free, daemon-free.  Run after editing model.yaml or info-hierarchy.md.
"""
from __future__ import annotations
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
YAML = ROOT / "docs" / "world-model" / "model.yaml"
INFO = ROOT / "docs" / "info-hierarchy.md"
SKILLS = ROOT / ".claude" / "skills"


def _load_yaml_raw() -> str:
    return YAML.read_text()


def _load_info() -> str:
    return INFO.read_text()


def _render_world_model(yaml_raw: str) -> str:
    lines = [
        "# World Model",
        "",
        "RSE fulfills the four-layer world model defined in `docs/world-model/model.yaml`.",
        "Use this skill to check conformance and understand RSE's governing laws.",
        "",
        "## Quick reference — L1 Invariants",
        "",
        "| ID | Principle |",
        "|----|-----------|",
    ]
    import re
    for m in re.finditer(r"- id: (P\d+)\s+principle: \"([^\"]+)\"", yaml_raw):
        lines.append(f"| {m.group(1)} | {m.group(2)} |")

    lines += [
        "",
        "## L2 Components",
        "",
        "| Package | Module | Key ops |",
        "|---------|--------|---------|",
    ]
    for m in re.finditer(
        r"(\w+):\s+\{module: \"([^\"]+)\",\s+ops: \[([^\]]+)\]", yaml_raw
    ):
        ops = m.group(3).replace(", ", " · ")
        lines.append(f"| {m.group(1)} | `{m.group(2)}` | {ops} |")

    lines += [
        "",
        "## How to check conformance",
        "",
        "```bash",
        "# GPU-free, daemon-free",
        "python scripts/check_world_model.py",
        "",
        "# Check a specific range",
        "python scripts/check_world_model.py --base HEAD~1 --head HEAD",
        "",
        "# Regenerate these skill files after editing model.yaml or info-hierarchy.md",
        "python scripts/gen_world_model_skills.py",
        "```",
        "",
        "## Authoritative sources",
        "",
        "- `docs/world-model/model.yaml` — machine-readable (L1–L4 schema)",
        "- `docs/world-model/README.md` — human reference",
        "- `docs/architecture/federation-and-search-engine.md` — §1a prose form",
        "- `docs/architecture/federation-ops-and-invariants.md` — §13b HR specs",
        "",
        "_Generated by scripts/gen_world_model_skills.py — do not hand-edit._",
    ]
    return "\n".join(lines) + "\n"


def _render_info_hierarchy(info_raw: str) -> str:
    header = [
        "# Info Hierarchy",
        "",
        "RSE's DIKW doctrine ladder — how data climbs to wisdom and what each rung costs.",
        "",
    ]
    body = info_raw.split("\n", 1)[1] if info_raw.startswith("#") else info_raw
    footer = [
        "",
        "_Source: `docs/info-hierarchy.md` — generated by scripts/gen_world_model_skills.py._",
    ]
    return "\n".join(header) + body + "\n".join(footer) + "\n"


def main() -> None:
    if not YAML.exists():
        sys.exit(f"ERROR: {YAML} not found")
    if not INFO.exists():
        sys.exit(f"ERROR: {INFO} not found")

    SKILLS.mkdir(parents=True, exist_ok=True)

    yaml_raw = _load_yaml_raw()
    info_raw = _load_info()

    wm = SKILLS / "world-model.md"
    wm.write_text(_render_world_model(yaml_raw))
    print(f"wrote {wm.relative_to(ROOT)}")

    ih = SKILLS / "info-hierarchy.md"
    ih.write_text(_render_info_hierarchy(info_raw))
    print(f"wrote {ih.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
