#!/usr/bin/env python3
"""WS-D: generate .claude/skills/ from docs/world-model/model.yaml + docs/info-hierarchy.md.

GPU-free, daemon-free.  Run after editing model.yaml or info-hierarchy.md.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
YAML = ROOT / "docs" / "world-model" / "model.yaml"
INFO = ROOT / "docs" / "info-hierarchy.md"
SKILLS = ROOT / ".claude" / "skills"


def _load_yaml_raw() -> str:
    return YAML.read_text()


def _load_info() -> str:
    return INFO.read_text()


WM_DESC = (
    "RSE governing laws — the P0–P18 / HR1–HR41 invariant IDs, the component map, and how to "
    "check working-tree conformance. Read before changing indexing, extraction, GPU, or "
    "CPU-budget behaviour."
)
IH_DESC = (
    "RSE's DIKW doctrine ladder — how data climbs from data to wisdom, what each rung costs, "
    "and the compute-spend doctrine. Read when deciding where a new derived artifact belongs."
)


def _frontmatter(name: str, description: str) -> list[str]:
    """Claude Code discovers a skill by its frontmatter; without it the file never loads.

    The description is always quoted: an unquoted value containing ': ' parses as a nested
    mapping and the whole skill silently drops out of the listing.
    """
    return [
        "---",
        f"name: {name}",
        'description: "' + description.replace('"', "'") + '"',
        "---",
        "",
    ]


def _render_world_model(yaml_raw: str) -> str:
    lines = [
        *_frontmatter("world-model", WM_DESC),
        "# World Model",
        "",
        "RSE fulfills the four-layer world model defined in `docs/world-model/model.yaml`.",
        "Use this skill to check conformance and understand RSE's governing laws.",
        "",
        "## Quick reference — L1 Invariants",
        "",
        "| ID | Principle |",
        "|----|-----------|",
    ]
    import re
    for m in re.finditer(r"- id: (P\d+)\s+principle: \"([^\"]+)\"", yaml_raw):
        lines.append(f"| {m.group(1)} | {m.group(2)} |")

    lines += [
        "",
        "## L2 Components",
        "",
        "| Package | Module | Key ops |",
        "|---------|--------|---------|",
    ]
    for m in re.finditer(
        r"(\w+):\s+\{module: \"([^\"]+)\",\s+ops: \[([^\]]+)\]", yaml_raw
    ):
        ops = m.group(3).replace(", ", " · ")
        lines.append(f"| {m.group(1)} | `{m.group(2)}` | {ops} |")

    lines += [
        "",
        "## How to check conformance",
        "",
        "```bash",
        "# GPU-free, daemon-free",
        "python scripts/check_world_model.py",
        "",
        "# Check a specific range",
        "python scripts/check_world_model.py --base HEAD~1 --head HEAD",
        "",
        "# Regenerate these skill files after editing model.yaml or info-hierarchy.md",
        "python scripts/gen_world_model_skills.py",
        "```",
        "",
        "## Authoritative sources",
        "",
        "- `docs/world-model/model.yaml` — machine-readable (L1–L4 schema)",
        "- `docs/world-model/README.md` — human reference",
        "- `docs/architecture/federation-and-search-engine.md` — §1a prose form",
        "- `docs/architecture/federation-ops-and-invariants.md` — §13b HR specs",
        "",
        "_Generated by scripts/gen_world_model_skills.py — do not hand-edit._",
    ]
    return "\n".join(lines) + "\n"


def _render_info_hierarchy(info_raw: str) -> str:
    header = [
        *_frontmatter("info-hierarchy", IH_DESC),
        "# Info Hierarchy",
        "",
        "RSE's DIKW doctrine ladder — how data climbs to wisdom and what each rung costs.",
        "",
    ]
    body = info_raw.split("\n", 1)[1] if info_raw.startswith("#") else info_raw
    footer = [
        "",
        "_Source: `docs/info-hierarchy.md` — generated by scripts/gen_world_model_skills.py._",
    ]
    return "\n".join(header) + body + "\n".join(footer) + "\n"


def main() -> None:
    if not YAML.exists():
        sys.exit(f"ERROR: {YAML} not found")
    if not INFO.exists():
        sys.exit(f"ERROR: {INFO} not found")

    yaml_raw = _load_yaml_raw()
    info_raw = _load_info()

    # One directory per skill with a SKILL.md inside — a flat <name>.md is never discovered.
    for name, text in (
        ("world-model", _render_world_model(yaml_raw)),
        ("info-hierarchy", _render_info_hierarchy(info_raw)),
    ):
        out = SKILLS / name / "SKILL.md"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(text)
        print(f"wrote {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
